### ISSUE TITLE
User is not logged in

### ISSUE THREAD

**Issue by emerchan** [maxkferg/meteor-facebook-collections#6] opened 2014-11-20 15:57 UTC
Hello, I am having the message: "User is not logged in" in the console, the code that I am using is pretty simple, I dont know If I am using it in the right way:

```
if (Meteor.isClient) {
    Template.hello.helpers({
    friends: function () {
      return FacebookCollections.getFriends("me",["47362876287364","Eduardo"],100);
    }
  });
}
```

HTML

```
<body>
  <h1>Welcome to Meteor!</h1>
  {{> loginButtons}}
  {{> hello}}
</body>

<template name="hello">
  {{#each friends}}
      {{name}}
{{/each}}
</template>
```

**Comment by maxkferg** [comment] 2014-11-20 19:19
This is directly related to issue #5. FacebookCollections.getFriends can only be called once the user is logged in with Facebook, if it is called earlier it will raise the error you described. Issue #5 describes the problem and our plans to fix it. Pull requests are welcome.

Closed: Duplicate of issues #4 and #5.

**Closed as completed by maxkferg** 2014-11-20 19:19 UTC

**Comment by emerchan** [comment] 2014-11-20 19:39
Inside the web console I can check the user logged in and I can see the information Using Meteor.user() actually I am loggedin.

Thanks

**Comment by maxkferg** [comment] 2014-11-20 20:05
And is the Meteor.user().services.facebook.accessToken available on the client. If you have removed autopublish then you need to publish/subscribe the facebook accessToken.

**Comment by emerchan** [comment] 2014-11-21 03:27
Perfect. Thank you

**Comment by icm** [comment] 2015-01-31 22:20
can you share how you got your simple example to work?
